# Backpropagation Part 2

In [16]:
import numpy as np
from tensorflow.keras.layers import Softmax, Conv2D, Dense, Input
from tensorflow.keras.losses import CategoricalCrossentropy

In [45]:
softmax = Softmax()


def my_softmax(y):
    z = np.sum(np.exp(y), axis=1, keepdims=True)
    log_probs = y - np.log(z)
    return np.exp(log_probs)

def my_better_softmax(y):
    shifted_logits = y - np.max(y, axis=1, keepdims=True)
    z = np.sum(np.exp(shifted_logits), axis=1, keepdims=True)
    log_probs = shifted_logits - np.log(z)
    return np.exp(log_probs)

In [46]:
y = np.array([[-200, 100, 5], [-200, 100, -5]]).astype(np.float64) * 1000
print(softmax(y))
print(my_softmax(y))
print(my_better_softmax(y))

tf.Tensor(
[[0. 1. 0.]
 [0. 1. 0.]], shape=(2, 3), dtype=float32)
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]]


/tmp/ipykernel_358000/838545724.py:5: RuntimeWarning: overflow encountered in exp
  z = np.sum(np.exp(y), axis=1, keepdims=True)


In [75]:
y_true = np.array([[0.3, 0.4, 0.3], [0.5, 0.5, 0.0], [1.0, 0.0, 0.0]])
y_pred = np.array([[0.3, 0.4, 0.29], [0.5, 0.5, 0.01], [0.99, 0.01, 0.01]])
cce = CategoricalCrossentropy()
cce(y_true, y_pred).numpy()

0.6040394277047364

In [76]:
def my_cross_entropy(y_true, y_pred):
    log_probs = np.log(y_pred)
    return -np.sum(y_true * log_probs) / y_true.shape[0]

my_cross_entropy(y_true, y_pred)

0.6007559857537915

In [80]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
x = np.ones((3, 3))
np.pad(x, [(1, 1), (1, 1)], mode)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
x = np.ones((1, 5, 5, 3))
f = 2 * np.ones((2, 3, 3))

np.sum(x[0, 0:3, 0:3, :] * f[0])

54.0

In [21]:
x = Input((1, 5, 5, 3))
conv2d = Conv2D(5,3)(x)
dense = Dense(10)(conv2d)

In [22]:
print(conv2d)
print(dense)

KerasTensor(type_spec=TensorSpec(shape=(None, 1, 3, 3, 5), dtype=tf.float32, name=None), name='conv2d_3/squeeze_batch_dims/Reshape_1:0', description="created by layer 'conv2d_3'")
KerasTensor(type_spec=TensorSpec(shape=(None, 1, 3, 3, 10), dtype=tf.float32, name=None), name='dense_3/BiasAdd:0', description="created by layer 'dense_3'")


In [24]:
np.matmul(np.ones((1, 5, 5, 3)), np.ones((3, 10))).shape 

(1, 5, 5, 10)